library(Seurat)
library(SeuratDisk)

head(yizhen)
yizhen <- SetIdent(yizhen, value = 'orig.ident')
table(yizhen$orig.ident)
yizhen <- RenameIdents(yizhen, 'WT' = 'WTB', 'B' = 'WTB')
yizhen$background <- yizhen@active.ident

library(escape)

gene.sets1 <- getGeneSets(library = "C5", gene.sets = c("GOBP_MICROGLIA_DIFFERENTIATION",
'GOBP_MICROGLIAL_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE','GOBP_MICROGLIAL_CELL_MEDIATED_CYTOTOXICITY',
'GOBP_MICROGLIAL_CELL_MIGRATION','GOBP_MICROGLIAL_CELL_PROLIFERATION','GOBP_REGULATION_OF_MICROGLIAL_CELL_ACTIVATION',
'GOBP_MACROPHAGE_ACTIVATION','GOBP_MACROPHAGE_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE',
'GOBP_MACROPHAGE_APOPTOTIC_PROCESS',
'GOBP_MACROPHAGE_CHEMOTAXIS',
'GOBP_MACROPHAGE_COLONY_STIMULATING_FACTOR_PRODUCTION',
'GOBP_MACROPHAGE_COLONY_STIMULATING_FACTOR_SIGNALING_PATHWAY',
'GOBP_MACROPHAGE_CYTOKINE_PRODUCTION',
'GOBP_MACROPHAGE_DIFFERENTIATION',
'GOBP_MACROPHAGE_FUSION',
'GOBP_MACROPHAGE_INFLAMMATORY_PROTEIN_1_ALPHA_PRODUCTION',
'GOBP_MACROPHAGE_MIGRATION',
'GOBP_MACROPHAGE_PROLIFERATION',
'GOBP_REGULATION_OF_MACROPHAGE_ACTIVATION',
'GOBP_REGULATION_OF_MACROPHAGE_APOPTOTIC_PROCESS',
'GOBP_REGULATION_OF_MACROPHAGE_CHEMOTAXIS',
'GOBP_REGULATION_OF_MACROPHAGE_DERIVED_FOAM_CELL_DIFFERENTIATION',
'GOBP_REGULATION_OF_MACROPHAGE_DIFFERENTIATION',
'GOBP_REGULATION_OF_MACROPHAGE_FUSION',
'GOBP_REGULATION_OF_MACROPHAGE_MIGRATION',
'GOBP_REGULATION_OF_MACROPHAGE_PROLIFERATION',
'HP_ABNORMAL_MACROPHAGE_MORPHOLOGY',
'GOBP_RESPONSE_TO_MACROPHAGE_COLONY_STIMULATING_FACTOR',
'GOBP_REGULATION_OF_CELLULAR_RESPONSE_TO_MACROPHAGE_COLONY_STIMULATING_FACTOR_STIMULUS',
'GOBP_RESPONSE_TO_MACROPHAGE_COLONY_STIMULATING_FACTOR',
'GOBP_GRANULOCYTE_MACROPHAGE_COLONY_STIMULATING_FACTOR_PRODUCTION',
'GOBP_POSITIVE_REGULATION_OF_GRANULOCYTE_MACROPHAGE_COLONY_STIMULATING_FACTOR_PRODUCTION',
'GOBP_PHAGOCYTOSIS',
'GOBP_PHAGOCYTOSIS_ENGULFMENT',
'GOBP_PHAGOCYTOSIS_RECOGNITION',
'GOBP_T_CELL_ACTIVATION',
'GOBP_T_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE',
'GOBP_T_CELL_ACTIVATION_VIA_T_CELL_RECEPTOR_CONTACT_WITH_ANTIGEN_BOUND_TO_MHC_MOLECULE_ON_ANTIGEN_PRESENTING_CELL',
'GOBP_T_CELL_ANTIGEN_PROCESSING_AND_PRESENTATION',
'GOBP_T_CELL_APOPTOTIC_PROCESS',
'GOBP_T_CELL_CHEMOTAXIS',
'GOBP_T_CELL_CYTOKINE_PRODUCTION',
'GOBP_T_CELL_DIFFERENTIATION'),species = 'Mus musculus')

ES <- enrichIt(obj = yizhen,
gene.sets = gene.sets1,
groups = 1000, cores = 1)
